// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...\n/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1gOdi7HeS6C4TT8BlV9gQ3AhmLiqdzI',
    appId: '1:21016179736:web:47381986ebfa1cfd5e3f6d',
    messagingSenderId: '21016179736',
    projectId: 'ecolifeunit',
    authDomain: 'ecolifeunit.firebaseapp.com',
    storageBucket: 'ecolifeunit.firebasestorage.app',
    measurementId: 'G-BBPB54508Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk1gOdi7HeS6C4TT8BlV9gQ3AhmLiqdzI',
    appId: '1:21016179736:android:e4f4139ef4ed26f65e3f6d',
    messagingSenderId: '21016179736',
    projectId: 'ecolifeunit',
    storageBucket: 'ecolifeunit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk1gOdi7HeS6C4TT8BlV9gQ3AhmLiqdzI',
    appId: '1:21016179736:ios:e4f4139ef4ed26f65e3f6d',
    messagingSenderId: '21016179736',
    projectId: 'ecolifeunit',
    storageBucket: 'ecolifeunit.firebasestorage.app',
    iosBundleId: 'Eco.LifeUnit1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk1gOdi7HeS6C4TT8BlV9gQ3AhmLiqdzI',
    appId: '1:21016179736:ios:e4f4139ef4ed26f65e3f6d',
    messagingSenderId: '21016179736',
    projectId: 'ecolifeunit',
    storageBucket: 'ecolifeunit.firebasestorage.app',
    iosBundleId: 'Eco.LifeUnit1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk1gOdi7HeS6C4TT8BlV9gQ3AhmLiqdzI',
    appId: '1:21016179736:web:47381986ebfa1cfd5e3f6d',
    messagingSenderId: '21016179736',
    projectId: 'ecolifeunit',
    authDomain: 'ecolifeunit.firebaseapp.com',
    storageBucket: 'ecolifeunit.firebasestorage.app',
    measurementId: 'G-BBPB54508Y',
  );
}